pipeline {
    agent any

    stages {

stage('Create ArgoCD Application') {
            steps {
                sh '''
                  set -e

                  export AWS_REGION=us-east-1
                  export CLUSTER_NAME=hello-devops-production-cluster

                  echo "🔹 Updating kubeconfig..."
                  aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                  echo "🔹 Creating ArgoCD Application..."

                  kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmedlebshten/ArgoCD-Pipeline.git
    targetRevision: HEAD
    path: ArgoCD-Application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF

                  echo "🎉 ArgoCD Application Created Successfully!"
                '''
            }
        }
        }
}