pipeline {
    agent any

    stages {

        stage('Create Monitoring Application') {
            steps {
                sh '''
                  set -e

                  export AWS_REGION=us-east-1
                  export CLUSTER_NAME=hello-devops-production-cluster

                  echo "🔹 Updating kubeconfig..."
                  aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                  echo "🔹 Creating ArgoCD Monitoring Application..."

                  kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmedlebshten/ArgoCD-Pipeline.git
    targetRevision: HEAD
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF

                  echo "🎉 Monitoring Application Created Successfully!"
                '''
            }
        }
    }
}
